import { Amplify } from 'aws-amplify';
// amplify_outputs.json is generated by `ampx sandbox` or `ampx pipeline-deploy`
// It is gitignored — every developer runs the sandbox to generate it locally

try {
  const outputs = require('../../amplify_outputs.json');
  Amplify.configure(outputs.default ?? outputs);
} catch {
  console.warn('Amplify outputs not found. Run `yarn amplify-sandbox` before using backend features.');
}
